// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_small_gauge_scale_png);    // assets/Small_Gauge_Scale.png
LV_IMG_DECLARE(ui_img_dark_led_png);    // assets/Dark_LED.png
LV_IMG_DECLARE(ui_img_red_led_png);    // assets/Red_LED.png
LV_IMG_DECLARE(ui_img_small_gauge_needle_png);    // assets/Small_Gauge_Needle.png
LV_IMG_DECLARE(ui_img_red_bug__png);    // assets/red_bug_.png
LV_IMG_DECLARE(ui_img_grn_bug__png);    // assets/grn_bug_.png

// FONTS
LV_FONT_DECLARE(ui_font_courierBold);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
